version: '3'
services:
  nginx: # Nginx Service
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - php

  php: # PHP Service
    build:
        context: php
        dockerfile: Dockerfile
        args:
            user: ${USER}
            uid: ${USER_ID}
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - mysql

  mysql: # MySQL Service
    image: mysql:5.7.44
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - app-network

volumes:
    mysql-data:

networks:
  app-network:
    driver: bridge
